print("First I need some information from you.")
name = input("What is your name: ")
print("Hi " + name + " How are you. ")
print("I hope you are Great. ")
print("Now I need to know little more about you. ")
age = input("How old are you? ")
print("WoW you are " + age + " years old. ")
game = input("Would you like to play a GAME: ")
if game == "yes":
    print("LETS DO IT")
else:
    print("Sorry we will play anyway.")
place = input("What is your favorite place? ")
friend = input("Who is your best friend? ")
city = input("What city do you live in? ")
print("We went to the " + place + " to kill some time")
print(name + " and " + friend + " are covered in a slime")
print("They came from " + city + " where burgers are big.")
print("But no body knows that " + name + " wears a wig")